### PR TITLE
Utilize: The class `MyApp` created in `LUA_FUNCTION`

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by SupinePandora43** [comment]
but what it changes?

**Comment by dvdvideo1234** [comment]
@SupinePandora43  Consolidates the logic in the `MyApp` class. Nothing functional

**Comment by SupinePandora43** [comment]
@dvdvideo1234 can you help with #1 , (3rd) ???

**Comment by SupinePandora43** [comment]
sorry, but `MyApp` is place only for Ultralight's code, and i think saving `LUA` state is bad idea...

**Pull request closed without merging**
